name: Deploy to Kubernetes

on: 
  schedule:
    - cron: "*/2 * * * *"
  
  workflow_dispatch:
  
  push:
    branches:
      - develop
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with: 
          helm-version: '3.8.0'

      - name: Check Version
        shell: bash
        run: |
          helm version

